daemon off;
user nginx;
events {}

http {
  include mime.types;
  default_type application/octet-stream;

  server {
    listen 8080;

    # ruTorrent

    location /RPC2 {
      include scgi_params;
      scgi_pass unix:/var/run/rtorrent/rpc.socket;
    }

    location / {
      root /etc/nginx/rutorrent;
      index index.html;
    }

    location ~ \.php$ {
      root /etc/nginx/rutorrent;
      fastcgi_pass unix:/var/run/php-fpm/php-fpm.socket;
      fastcgi_index index.php;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      fastcgi_param RU_PROFILE_PATH /var/rutorrent/share;
      fastcgi_param RU_SCGI_HOST unix:///var/run/rtorrent/rpc.socket;
      fastcgi_param RU_SCGI_PORT 0;
      include fastcgi_params;
    }
  }
}
